"""Generate SD CSV columns from the same schema as BLE and the receiver."""
import argparse
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
schema = json.loads((root / 'protocol/outdoor-v1.json').read_text())
widths = {'u8': 1, 'bool': 1, 'u16': 2, 'i16': 2, 'u32': 4, 'i32': 4, 'u64': 8}
columns = ['timestamp_utc', 'clock_synced', 'sequence', 'uptime_ms', 'enabled_mask', 'valid_mask']
lines = ['/* Generated by outdoor/protocol/generate_csv.py. */',
         'static const struct csv_field csv_fields[] = {']
size = schema['headerSize']
for sensor in schema['sensors']:
    key = sensor['key']
    columns.append(f'{key}.error')
    offset = 2
    for field in sensor['fields']:
        columns.append(f"{field.get('source', key)}.{field['key']}" + (f"[{field['unit']}]" if field.get('unit') else ''))
        divisor = round(1 / field.get('scale', 1))
        assert divisor in (1, 100, 1000)
        lines.append(f"    {{ {sensor['id']}, {offset}, {widths[field['type']]}, {int(field['type'].startswith('i'))}, {int(field.get('format') == 'hex')}, {divisor} }},")
        offset += widths[field['type']]
    size += offset + 4
lines += ['};', 'static const size_t csv_sensor_sizes[8] = {0, ' + ', '.join(str(2 + sum(widths[f['type']] for f in s['fields'])) for s in schema['sensors']) + '};',
          '#define SD_LOG_PACKET_MAX ' + str(size),
          '#define SD_CSV_HEADER ' + json.dumps(','.join(columns) + '\r\n', ensure_ascii=True), '']
target = root / 'firmware/logging/include/sd_csv_schema.h'
content = '\n'.join(lines)
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
if args.check:
    if not target.exists() or target.read_text() != content:
        raise SystemExit('Stale SD CSV schema; run python3 outdoor/protocol/generate_csv.py')
else:
    target.write_text(content)
