"""Generate the C wire encoder from the schema shared with the web receiver."""
import argparse
import json
import uuid
from pathlib import Path

root = Path(__file__).resolve().parents[1]
schema = json.loads((root / "protocol/outdoor-v1.json").read_text())
target = root / "firmware/telemetry"
drivers = {s["key"]: s.get("driver", s["key"]) for s in schema["sensors"]}
header = ['/* Generated by outdoor/protocol/generate.py; edit outdoor-v1.json. */',
          '#ifndef OUTDOOR_TELEMETRY_H_', '#define OUTDOOR_TELEMETRY_H_',
          '#include <stddef.h>', '#include <stdint.h>']
header += [f'#include <{drivers[s["key"]]}.h>' for s in schema["sensors"]]
header += [f'#define TELEMETRY_MAX_SIZE {schema["maxSize"]}',
           f'#define TELEMETRY_HEADER_SIZE {schema["headerSize"]}',
           f'#define TELEMETRY_FRAGMENT_HEADER_SIZE {schema["fragmentHeaderSize"]}',
           f'#define TELEMETRY_SERVICE_UUID "{schema["serviceUuid"]}"',
           f'#define TELEMETRY_CHARACTERISTIC_UUID "{schema["characteristicUuid"]}"',
           'struct telemetry_sample {', '\tuint32_t sequence;', '\tuint64_t uptime_ms;',
           '\tuint16_t enabled_mask;']
for label, key in [('SERVICE', 'serviceUuid'), ('CHARACTERISTIC', 'characteristicUuid')]:
    encoded = ', '.join(f'0x{byte:02x}' for byte in uuid.UUID(schema[key]).bytes[::-1])
    header.insert(6, f'#define TELEMETRY_{label}_UUID_BYTES {encoded}')
for sensor in schema["sensors"]:
    key = sensor["key"]
    header.append(f'\tstruct {{ int16_t error; struct {key}_sample value; }} {key};')
header += ['};', 'size_t telemetry_encode(const struct telemetry_sample *sample, uint8_t *output, size_t capacity);',
           'size_t telemetry_fragment(const uint8_t *frame, size_t length, size_t offset, uint8_t *output, size_t capacity);',
           'int telemetry_ble_init(void);', 'void telemetry_ble_publish(const struct telemetry_sample *sample);', '#endif', '']

source = '''/* Generated by outdoor/protocol/generate.py; edit outdoor-v1.json. */
#include <telemetry.h>
#include <stdbool.h>
#include <string.h>
struct writer { uint8_t *bytes; size_t size; size_t capacity; bool failed; };
static void put(struct writer *w, uint64_t value, size_t width)
{
    if (w->size + width > w->capacity) { w->failed = true; return; }
    for (size_t i = 0; i < width; i++) { w->bytes[w->size++] = value >> (8 * i); }
}
size_t telemetry_encode(const struct telemetry_sample *sample, uint8_t *output, size_t capacity)
{
    if (!sample || !output || capacity < TELEMETRY_HEADER_SIZE || (sample->enabled_mask & ~0x7f)) { return 0; }
    struct writer w = { output, 0, capacity, false };
    uint16_t valid = 0;
'''
for sensor in schema["sensors"]:
    source += f'    if ((sample->enabled_mask & {1 << (sensor["id"]-1)}) && sample->{sensor["key"]}.error == 0) {{ valid |= {1 << (sensor["id"]-1)}; }}\n'
source += '''    put(&w, 'O', 1); put(&w, 'E', 1); put(&w, 1, 1); put(&w, TELEMETRY_HEADER_SIZE, 1);
    put(&w, 0, 2); put(&w, sample->enabled_mask, 2); put(&w, valid, 2); put(&w, 0, 2);
    put(&w, sample->sequence, 4); put(&w, sample->uptime_ms, 8);
'''
widths = {"u8": 1, "bool": 1, "u16": 2, "i16": 2, "u32": 4, "i32": 4, "u64": 8}
for sensor in schema["sensors"]:
    key = sensor["key"]
    size = 2 + sum(widths[f["type"]] for f in sensor["fields"])
    source += f'''    if (sample->enabled_mask & {1 << (sensor["id"]-1)}) {{
        if (sample->{key}.error > 0) {{ return 0; }}
        put(&w, {sensor["id"]}, 1); put(&w, {sensor.get("version", 1)}, 1);
        put(&w, sample->{key}.error == 0 ? {size} : 2, 2);
        put(&w, (uint16_t)sample->{key}.error, 2);
        if (sample->{key}.error == 0) {{
'''
    for field in sensor["fields"]:
        source += f'            put(&w, sample->{key}.value.{field["key"]}, {widths[field["type"]]});\n'
    source += '        }\n    }\n'
source += '''    if (w.failed || w.size > TELEMETRY_MAX_SIZE) { return 0; }
    output[4] = w.size; output[5] = w.size >> 8;
    return w.size;
}
size_t telemetry_fragment(const uint8_t *frame, size_t length, size_t offset, uint8_t *output, size_t capacity)
{
    if (!frame || !output || length < TELEMETRY_HEADER_SIZE || length > TELEMETRY_MAX_SIZE || offset >= length || capacity <= TELEMETRY_FRAGMENT_HEADER_SIZE) { return 0; }
    struct writer w = { output, 0, capacity, false };
    put(&w, 'O', 1); put(&w, 'F', 1); put(&w, 1, 1); put(&w, 0, 1);
    memcpy(output + 4, frame + 12, 4); w.size += 4;
    put(&w, length, 2); put(&w, offset, 2);
    size_t count = length - offset;
    if (count > capacity - w.size) { count = capacity - w.size; }
    memcpy(output + w.size, frame + offset, count);
    return w.size + count;
}
'''
files = {target / "include/telemetry.h": '\n'.join(header), target / "telemetry_encode.c": source}
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
for path, content in files.items():
    if args.check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f'Stale generated file: {path}; run python3 outdoor/protocol/generate.py')
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
