/* Generated by outdoor/protocol/generate.py; edit outdoor-v1.json. */
#ifndef OUTDOOR_TELEMETRY_H_
#define OUTDOOR_TELEMETRY_H_
#include <stddef.h>
#include <stdint.h>
#include <opt4001.h>
#define TELEMETRY_CHARACTERISTIC_UUID_BYTES 0xfd, 0xcf, 0xe7, 0x99, 0xe5, 0x67, 0x16, 0xa9, 0x8d, 0x46, 0x7f, 0xe7, 0x81, 0xcd, 0x2a, 0x72
#define TELEMETRY_SERVICE_UUID_BYTES 0xfd, 0xcf, 0xe7, 0x99, 0xe5, 0x67, 0x16, 0xa9, 0x8d, 0x46, 0x7f, 0xe7, 0x80, 0xcd, 0x2a, 0x72
#include <bme690.h>
#include <sgp41.h>
#include <stcc4.h>
#include <bmv080_driver.h>
#include <as3935.h>
#include <sfa40.h>
#define TELEMETRY_MAX_SIZE 512
#define TELEMETRY_HEADER_SIZE 24
#define TELEMETRY_FRAGMENT_HEADER_SIZE 12
#define TELEMETRY_SERVICE_UUID "722acd80-e77f-468d-a916-67e599e7cffd"
#define TELEMETRY_CHARACTERISTIC_UUID "722acd81-e77f-468d-a916-67e599e7cffd"
struct telemetry_sample {
	uint32_t sequence;
	uint64_t uptime_ms;
	uint16_t enabled_mask;
	struct { int16_t error; struct opt4001_sample value; } opt4001;
	struct { int16_t error; struct bme690_sample value; } bme690;
	struct { int16_t error; struct sgp41_sample value; } sgp41;
	struct { int16_t error; struct stcc4_sample value; } stcc4;
	struct { int16_t error; struct bmv080_sample value; } bmv080;
	struct { int16_t error; struct as3935_sample value; } as3935;
	struct { int16_t error; struct sfa40_sample value; } sfa40;
};
size_t telemetry_encode(const struct telemetry_sample *sample, uint8_t *output, size_t capacity);
size_t telemetry_fragment(const uint8_t *frame, size_t length, size_t offset, uint8_t *output, size_t capacity);
int telemetry_ble_init(void);
void telemetry_ble_publish(const struct telemetry_sample *sample);
#endif
