/* Generated by outdoor/protocol/generate.py; edit outdoor-v1.json. */
#include <telemetry.h>
#include <stdbool.h>
#include <string.h>
struct writer { uint8_t *bytes; size_t size; size_t capacity; bool failed; };
static void put(struct writer *w, uint64_t value, size_t width)
{
    if (w->size + width > w->capacity) { w->failed = true; return; }
    for (size_t i = 0; i < width; i++) { w->bytes[w->size++] = value >> (8 * i); }
}
size_t telemetry_encode(const struct telemetry_sample *sample, uint8_t *output, size_t capacity)
{
    if (!sample || !output || capacity < TELEMETRY_HEADER_SIZE || (sample->enabled_mask & ~0x7f)) { return 0; }
    struct writer w = { output, 0, capacity, false };
    uint16_t valid = 0;
    if ((sample->enabled_mask & 1) && sample->opt4001.error == 0) { valid |= 1; }
    if ((sample->enabled_mask & 2) && sample->bme690.error == 0) { valid |= 2; }
    if ((sample->enabled_mask & 4) && sample->sgp41.error == 0) { valid |= 4; }
    if ((sample->enabled_mask & 8) && sample->stcc4.error == 0) { valid |= 8; }
    if ((sample->enabled_mask & 16) && sample->bmv080.error == 0) { valid |= 16; }
    if ((sample->enabled_mask & 32) && sample->as3935.error == 0) { valid |= 32; }
    if ((sample->enabled_mask & 64) && sample->sfa40.error == 0) { valid |= 64; }
    put(&w, 'O', 1); put(&w, 'E', 1); put(&w, 1, 1); put(&w, TELEMETRY_HEADER_SIZE, 1);
    put(&w, 0, 2); put(&w, sample->enabled_mask, 2); put(&w, valid, 2); put(&w, 0, 2);
    put(&w, sample->sequence, 4); put(&w, sample->uptime_ms, 8);
    if (sample->enabled_mask & 1) {
        if (sample->opt4001.error > 0) { return 0; }
        put(&w, 1, 1); put(&w, 1, 1);
        put(&w, sample->opt4001.error == 0 ? 14 : 2, 2);
        put(&w, (uint16_t)sample->opt4001.error, 2);
        if (sample->opt4001.error == 0) {
            put(&w, sample->opt4001.value.millilux, 4);
            put(&w, sample->opt4001.value.mantissa, 4);
            put(&w, sample->opt4001.value.device_id, 2);
            put(&w, sample->opt4001.value.exponent, 1);
            put(&w, sample->opt4001.value.counter, 1);
        }
    }
    if (sample->enabled_mask & 2) {
        if (sample->bme690.error > 0) { return 0; }
        put(&w, 2, 1); put(&w, 1, 1);
        put(&w, sample->bme690.error == 0 ? 28 : 2, 2);
        put(&w, (uint16_t)sample->bme690.error, 2);
        if (sample->bme690.error == 0) {
            put(&w, sample->bme690.value.temperature_mc, 4);
            put(&w, sample->bme690.value.pressure_pa, 4);
            put(&w, sample->bme690.value.humidity_mpercent, 4);
            put(&w, sample->bme690.value.gas_resistance_ohm, 4);
            put(&w, sample->bme690.value.chip_id, 1);
            put(&w, sample->bme690.value.variant_id, 1);
            put(&w, sample->bme690.value.status, 1);
            put(&w, sample->bme690.value.measurement_index, 1);
            put(&w, sample->bme690.value.gas_index, 1);
            put(&w, sample->bme690.value.heater_resistance, 1);
            put(&w, sample->bme690.value.heater_current, 1);
            put(&w, sample->bme690.value.gas_wait, 1);
            put(&w, sample->bme690.value.gas_valid, 1);
            put(&w, sample->bme690.value.heater_stable, 1);
        }
    }
    if (sample->enabled_mask & 4) {
        if (sample->sgp41.error > 0) { return 0; }
        put(&w, 3, 1); put(&w, 2, 1);
        put(&w, sample->sgp41.error == 0 ? 28 : 2, 2);
        put(&w, (uint16_t)sample->sgp41.error, 2);
        if (sample->sgp41.error == 0) {
            put(&w, sample->sgp41.value.serial_number, 8);
            put(&w, sample->sgp41.value.raw_voc, 2);
            put(&w, sample->sgp41.value.raw_nox, 2);
            put(&w, sample->sgp41.value.self_test, 2);
            put(&w, sample->sgp41.value.temperature_ticks, 2);
            put(&w, sample->sgp41.value.humidity_ticks, 2);
            put(&w, sample->sgp41.value.nox_valid, 1);
            put(&w, sample->sgp41.value.conditioning, 1);
            put(&w, sample->sgp41.value.voc_index, 2);
            put(&w, sample->sgp41.value.nox_index, 2);
            put(&w, sample->sgp41.value.voc_index_valid, 1);
            put(&w, sample->sgp41.value.nox_index_valid, 1);
        }
    }
    if (sample->enabled_mask & 8) {
        if (sample->stcc4.error > 0) { return 0; }
        put(&w, 4, 1); put(&w, 1, 1);
        put(&w, sample->stcc4.error == 0 ? 30 : 2, 2);
        put(&w, (uint16_t)sample->stcc4.error, 2);
        if (sample->stcc4.error == 0) {
            put(&w, sample->stcc4.value.serial_number, 8);
            put(&w, sample->stcc4.value.product_id, 4);
            put(&w, sample->stcc4.value.temperature_mc, 4);
            put(&w, sample->stcc4.value.humidity_mpercent, 4);
            put(&w, sample->stcc4.value.co2_ppm, 2);
            put(&w, sample->stcc4.value.raw_temperature, 2);
            put(&w, sample->stcc4.value.raw_humidity, 2);
            put(&w, sample->stcc4.value.status, 2);
        }
    }
    if (sample->enabled_mask & 16) {
        if (sample->bmv080.error > 0) { return 0; }
        put(&w, 5, 1); put(&w, 1, 1);
        put(&w, sample->bmv080.error == 0 ? 45 : 2, 2);
        put(&w, (uint16_t)sample->bmv080.error, 2);
        if (sample->bmv080.error == 0) {
            put(&w, sample->bmv080.value.pm1_mass_milliug_m3, 4);
            put(&w, sample->bmv080.value.pm2_5_mass_milliug_m3, 4);
            put(&w, sample->bmv080.value.pm10_mass_milliug_m3, 4);
            put(&w, sample->bmv080.value.pm1_number_milliparticles_cm3, 4);
            put(&w, sample->bmv080.value.pm2_5_number_milliparticles_cm3, 4);
            put(&w, sample->bmv080.value.pm10_number_milliparticles_cm3, 4);
            put(&w, sample->bmv080.value.runtime_ms, 8);
            put(&w, sample->bmv080.value.sequence, 4);
            put(&w, sample->bmv080.value.age_ms, 4);
            put(&w, sample->bmv080.value.is_obstructed, 1);
            put(&w, sample->bmv080.value.is_outside_measurement_range, 1);
            put(&w, sample->bmv080.value.fresh, 1);
        }
    }
    if (sample->enabled_mask & 32) {
        if (sample->as3935.error > 0) { return 0; }
        put(&w, 6, 1); put(&w, 1, 1);
        put(&w, sample->as3935.error == 0 ? 26 : 2, 2);
        put(&w, (uint16_t)sample->as3935.error, 2);
        if (sample->as3935.error == 0) {
            put(&w, sample->as3935.value.energy, 4);
            put(&w, sample->as3935.value.distance_km, 2);
            put(&w, sample->as3935.value.interrupt_reason, 1);
            put(&w, sample->as3935.value.distance_code, 1);
            put(&w, sample->as3935.value.noise_floor, 1);
            put(&w, sample->as3935.value.watchdog_threshold, 1);
            put(&w, sample->as3935.value.spike_rejection, 1);
            put(&w, sample->as3935.value.minimum_lightnings, 1);
            put(&w, sample->as3935.value.tuning_capacitor, 1);
            put(&w, sample->as3935.value.trco_calibration, 1);
            put(&w, sample->as3935.value.srco_calibration, 1);
            put(&w, sample->as3935.value.lightning, 1);
            put(&w, sample->as3935.value.noise_high, 1);
            put(&w, sample->as3935.value.disturber, 1);
            put(&w, sample->as3935.value.storm_overhead, 1);
            put(&w, sample->as3935.value.out_of_range, 1);
            put(&w, sample->as3935.value.distance_valid, 1);
            put(&w, sample->as3935.value.indoor, 1);
            put(&w, sample->as3935.value.powered_down, 1);
            put(&w, sample->as3935.value.disturbers_masked, 1);
        }
    }
    if (sample->enabled_mask & 64) {
        if (sample->sfa40.error > 0) { return 0; }
        put(&w, 7, 1); put(&w, 1, 1);
        put(&w, sample->sfa40.error == 0 ? 35 : 2, 2);
        put(&w, (uint16_t)sample->sfa40.error, 2);
        if (sample->sfa40.error == 0) {
            put(&w, sample->sfa40.value.serial_number, 8);
            put(&w, sample->sfa40.value.product_id, 4);
            put(&w, sample->sfa40.value.hcho_millippb, 4);
            put(&w, sample->sfa40.value.humidity_mpercent, 4);
            put(&w, sample->sfa40.value.temperature_mc, 4);
            put(&w, sample->sfa40.value.raw_hcho, 2);
            put(&w, sample->sfa40.value.raw_humidity, 2);
            put(&w, sample->sfa40.value.raw_temperature, 2);
            put(&w, sample->sfa40.value.status, 1);
            put(&w, sample->sfa40.value.ready, 1);
            put(&w, sample->sfa40.value.within_specification, 1);
        }
    }
    if (w.failed || w.size > TELEMETRY_MAX_SIZE) { return 0; }
    output[4] = w.size; output[5] = w.size >> 8;
    return w.size;
}
size_t telemetry_fragment(const uint8_t *frame, size_t length, size_t offset, uint8_t *output, size_t capacity)
{
    if (!frame || !output || length < TELEMETRY_HEADER_SIZE || length > TELEMETRY_MAX_SIZE || offset >= length || capacity <= TELEMETRY_FRAGMENT_HEADER_SIZE) { return 0; }
    struct writer w = { output, 0, capacity, false };
    put(&w, 'O', 1); put(&w, 'F', 1); put(&w, 1, 1); put(&w, 0, 1);
    memcpy(output + 4, frame + 12, 4); w.size += 4;
    put(&w, length, 2); put(&w, offset, 2);
    size_t count = length - offset;
    if (count > capacity - w.size) { count = capacity - w.size; }
    memcpy(output + w.size, frame + offset, count);
    return w.size + count;
}
