add_subdirectory(buzzer)
if(CONFIG_APP_SENSOR_READ)
  add_subdirectory(common)
  add_subdirectory(opt4001)
  add_subdirectory(sgp41)
  add_subdirectory(stcc4)
  add_subdirectory(sht45)
  add_subdirectory(bme690)
  add_subdirectory(bmv080)
  add_subdirectory(as3935)
  add_subdirectory(sfa40)
endif()
