#!/usr/bin/env python3
"""Import the user's Bosch SDK locally; never copy proprietary files into Git."""
import argparse
import hashlib
from pathlib import Path
import zipfile

app = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('archive', type=Path)
args = parser.parse_args()
archive = args.archive.expanduser().resolve()
destination = app / '.local/bmv080-sdk-v11-2-0'
library = 'api/lib/arm_cortex_m33/arm_none_eabi_gcc/release'
required = ['api/inc/bmv080.h', 'api/inc/bmv080_defs.h',
            f'{library}/lib_bmv080.a', f'{library}/lib_postProcessor.a',
            'LICENSE.md', 'CHANGELOG.md', 'README.md']
with zipfile.ZipFile(archive) as sdk:
    for name in required:
        if name not in sdk.namelist():
            raise SystemExit(f'Missing Cortex-M33 SDK file: {name}')
    if b'11.2.0' not in sdk.read('CHANGELOG.md'):
        raise SystemExit('Expected BMV080 SDK v11.2.0')
    for name in required:
        output = destination / name
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(sdk.read(name))

def quoted(path: Path) -> str:
    return '"' + str(path).replace('\\', '\\\\').replace('"', '\\"') + '"'

config = app / '.local/bmv080_sdk.conf'
config.write_text('\n'.join([
    '# Generated by scripts/import_bmv080_sdk.py; not part of the default firmware.',
    'CONFIG_APP_BMV080=y', 'CONFIG_MAIN_STACK_SIZE=16384',
    'CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=65536',
    f'CONFIG_BMV080_SDK_INCLUDE_DIR={quoted(destination / "api/inc")}',
    f'CONFIG_BMV080_SDK_DRIVER_LIBRARY={quoted(destination / library / "lib_bmv080.a")}',
    f'CONFIG_BMV080_SDK_POSTPROCESSOR_LIBRARY={quoted(destination / library / "lib_postProcessor.a")}',
    '',
]))
(destination / 'IMPORT.txt').write_text(f'Archive: {archive.name}\nSHA256: {hashlib.sha256(archive.read_bytes()).hexdigest()}\n')
print(f'BMV080 SDK v11.2.0 (Cortex-M33 soft-float) imported to {destination}')
print(f'Build configuration: {config}')
